version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sendbird/laravel-backend
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /application_start.sh
      timeout: 300
      runas: root