export const testData=
{
    "_iid": "su-6bc30bc6-760f-4768-8851-de7c93a10685",
    "channelType": "group",
    "messageType": "user",
    "mentionType": "users",
    "mentionedUsers": [],
    "mentionedUserIds": [],
    "metaArrays": [],
    "extendedMessage": {},
    "createdAt": 1714557202188,
    "updatedAt": 0,
    "channelUrl": "310325-Single-1339973757",
    "data": "",
    "customType": "",
    "mentionedMessageTemplate": "",
    "parentMessage": null,
    "silent": false,
    "isOperatorMessage": false,
    "threadInfo": null,
    "reactions": [],
    "appleCriticalAlertOptions": null,
    "scheduledInfo": null,
    "suggestedReplies": null,
    "myFeedback": null,
    "myFeedbackStatus": "NOT_APPLICABLE",
    "forms": null,
    "_isContinuousMessages": false,
    "_scheduledStatus": null,
    "messageId": 3529354646,
    "parentMessageId": 0,
    "ogMetaData": null,
    "reqId": "rq-36f71583-e322-4f8a-a3db-1f88a877ba2c",
    "replyToChannel": false,
    "errorCode": 0,
    "sender": {
        "_iid": "su-6bc30bc6-760f-4768-8851-de7c93a10685",
        "userId": "325",
        "nickname": "Karan22",
        "plainProfileUrl": "https://outrightalk-backend.s3.amazonaws.com/assets/u/1713522271490742946.jpg",
        "requireAuth": false,
        "metaData": {},
        "connectionStatus": "nonavailable",
        "isActive": true,
        "lastSeenAt": null,
        "preferredLanguages": null,
        "friendDiscoveryKey": null,
        "friendName": null,
        "isBlockedByMe": false,
        "role": "none"
    },
    "sendingStatus": "succeeded",
    "message": "How can i help you??",
    "messageParams": null,
    "translations": {
        "ca": "Com et puc ajudar??",
        "zh-TW": "我怎麼幫你？",
        "ur": "میں آپ کی کیسے مدد کر سکتا ہوں؟؟",
        "bg": "Как мога да ти помогна??",
        "hi": "मैं आपकी कैसे मदद कर सकता हूँ??",
        "ru": "Могу я чем-нибудь помочь??",
        "fa": "چگونه می توانم به شما کمک کنم؟؟",
        "ar": "كيف يمكنني مساعدك؟؟",
        "zh-CN": "我怎么帮你？？",
        "pt": "Como posso ajudá-lo??",
        "hu": "Miben segíthetek??",
        "ko": "어떻게 도와 드릴까요??"
    },
    "translationTargetLanguages": [],
}

